services:
  savedbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: savedbot:latest
    container_name: savedbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BASE_DIR: /data
    volumes:
      - ./data:/data
    stop_grace_period: 40s
