services:
  - type: worker
    name: savedbot
    runtime: docker
    autoDeploy: true
    disk:
      name: savedbot-data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: BASE_DIR
        value: /data
      - key: TIMEZONE
        value: Europe/Moscow
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: SOO_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ALERT_CHAT_ID
        sync: false
